### PR TITLE
Add requirements for Read the Docs builds

### PR DESCRIPTION
**Pull request by namurphy**

### CODE REVIEW

**Comment by StanczakDominik** [comment]
Did you happen to set it up on RTD as well? We could set up its own docs CI.

**Comment by namurphy** [comment]
I did mostly set it up on RTD, and I just added a webhook just now.  I also gave you maintainer superpowers for this set of docs.

**Comment by StanczakDominik** [comment]
All right, thanks! :) Do you think you could sign us up for the RTD doc builder this time as per https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html#autobuild-documentation-for-pull-requests ? I've been reviewing VlaPy for a while and urgently need to make some pancakes. :pancakes:

**Comment by namurphy** [comment]
Yeah, that sounds like a good idea.  I added it as #5 so we don't forget.

**Comment by namurphy** [comment]
[There be docs here!](https://plasmapy-nei.readthedocs.io/en/latest/)

**Pull request merged**
